### model
model_name_or_path: PATH_TO_YOUR_MODEL
trust_remote_code: true

### method
stage: sft
do_train: false
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: DeepThink3D_SFT_data
template: llama3
cutoff_len: 10000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: PATH_TO_YOUR_OUTPUT_DIR
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 6
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2

## eval
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 10

report_to: wandb